#! /usr/bin/env python3

import gzip
import argparse
import re


PAGE_RE = re.compile(r"^(.+)\@([-:,0-9]+)$")
RANGE_RE = re.compile(r"^([-0-9]*)\:([-0-9]*)$")
BACKGROUND_ATTRS_RE = re.compile(
        r'^<background\s*(.*)\s*\/>$'
        )
BACKGROUND_ATTR_RE = re.compile(r'^([a-z]+)\=\"([^"]*)\"\s*')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-o', '--output', metavar="OUTPUT.XO{J,PP}",
        required=True)
    parser.add_argument('inputs', metavar="INPUT.XO{J,PP}[@m:n]", nargs="+")
    parser.add_argument(
        '-d', '--delete-layers', metavar='LAYER', type=int, nargs='*',
        help='Layers to delete, 1-based', default=[])

    args = parser.parse_args()

    out_lines = []

    for i_input, input_name in enumerate(args.inputs):

        # {{{ parse page_slices

        page_slices = []
        page_match = PAGE_RE.match(input_name)
        if page_match is not None:
            input_name = page_match.group(1)
            page_ranges = page_match.group(2)
            for page_range in page_ranges.split(","):
                if ":" in page_range:
                    start = None
                    end = None

                    range_match = RANGE_RE.match(page_range)
                    if range_match is not None:
                        if range_match.group(1):
                            start = int(range_match.group(1))
                            if start > 0:
                                start -= 1
                        if range_match.group(2):
                            end = int(range_match.group(2))
                            if end > 0:
                                end -= 1

                    page_slices.append(slice(start, end))
                else:
                    p = int(page_range)
                    if p > 0:
                        page_slices.append(slice(p-1, p))
                    elif p == -1:
                        page_slices.append(slice(p, None))
                    else:
                        page_slices.append(slice(p, p+1))

        else:
            page_slices.append(slice(None))

        # }}}

        with gzip.open(input_name, "rb") as inf:
            lines = list(inf.readlines())

        assert lines[-1].strip() == b"</xournal>"
        lines = lines[:-1]

        num_pages = len([
            l for l in lines if l.strip().startswith(b"<page")
            ])

        pages = set()
        for ps in page_slices:
            pages.update(range(*ps.indices(num_pages)))

        print("%s: %s" % (input_name, [pnr+1 for pnr in sorted(pages)]))

        i = 0

        # {{{ skip/copy header

        while not lines[i].startswith(b"<page"):
            # only copy header for first document
            if i_input == 0:
                out_lines.append(lines[i])
            i += 1

        # }}}

        ignoring_layer = False
        ignoring_page = False

        last_background_pdf_attrs = {}
        had_pdf_filename = False

        page_idx = -1
        while i < len(lines):
            line = lines[i]
            i += 1

            is_pdf_filename = False

            if line.startswith(b"<background"):
                background_attrs_match = BACKGROUND_ATTRS_RE.match(
                        line.decode().strip())
                assert background_attrs_match

                attrs_str = background_attrs_match.group(1)
                attrs = {}
                while True:
                    attr_match = BACKGROUND_ATTR_RE.match(attrs_str)
                    if attr_match:
                        attrs[attr_match.group(1)] = attr_match.group(2)
                        attrs_str = attrs_str[attr_match.end():]
                    else:
                        assert not attrs_str.strip(), attrs_str
                        break

                if attrs["type"] == "pdf":
                    if "filename" in attrs:
                        last_background_pdf_attrs["filename"] = attrs["filename"]
                        last_background_pdf_attrs["domain"] = attrs["domain"]
                        is_pdf_filename = True

                    elif not had_pdf_filename:
                        attrs.update(last_background_pdf_attrs)
                        new_attrs_str = b" ".join(
                                b'%s="%s"' % (k.encode(), v.encode())
                                for k, v in attrs.items())
                        line = b"<background %s/>\n" % new_attrs_str

            if ignoring_page:
                if line.strip().startswith(b"</page"):
                    ignoring_page = False
            elif ignoring_layer:
                if line.strip().startswith(b"</layer"):
                    ignoring_layer = False
            else:
                if line.strip().startswith(b"<page"):
                    layer_idx = 0
                    page_idx += 1
                    if page_idx not in pages:
                        ignoring_page = True
                    else:
                        out_lines.append(line)
                elif line.strip().startswith(b"<layer"):
                    layer_idx += 1
                    if layer_idx in args.delete_layers:
                        ignoring_layer = True
                    else:
                        out_lines.append(line)
                else:
                    if is_pdf_filename:
                        had_pdf_filename = True

                    out_lines.append(line)

    out_lines.append(b"</xournal>")

    with gzip.open(args.output, "wb") as outf:
        outf.write(b"".join(out_lines))


if __name__ == "__main__":
    main()

# vim: foldmethod=marker
